# Generated by Django 5.0.1 on 2026-02-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scrummeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrummeeting',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
