# Generated by Django 5.0.1 on 2026-02-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scrummeeting_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitlog',
            name='branch',
            field=models.CharField(blank=True, default='main', max_length=200),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='commit_author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='commit_author_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='commit_sha',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='files_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='is_meaningful',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='lines_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='lines_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commit_logs', to='main.project'),
        ),
        migrations.AddField(
            model_name='commitlog',
            name='trivial_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_owner',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='github_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='last_commit_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commitlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='main.task'),
        ),
    ]
