# Generated by Django 5.0.1 on 2026-02-17 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_task_assigned_to_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='main.phase'),
        ),
    ]
