# Generated by Django 5.0.1 on 2026-02-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sprint_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('installation_id', models.CharField(max_length=255)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
