# Generated by Django 5.0.1 on 2026-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pendingrepodeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('PROJECT_MANAGER', 'Project Manager'), ('TEAM_LEAD', 'Team Lead')], default='EMPLOYEE', max_length=20),
        ),
    ]
